# Generated by Django 2.0.5 on 2018-09-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Massege',
        ),
    ]
